from os import environ

env = Environment(ENV       = { 'TERM' : environ['TERM'] },
                  CXX       = 'clang++',
                  CXXFLAGS  = ['-std=c++11',
                               '-O', '-flto',
                               '-Wall', '-Werror', '-Wextra', '-pedantic'])

env.Program('seiken.out', Glob('*.cpp'))
