from os import environ

env = Environment(ENV      = {'TERM' : environ['TERM']},
                  CXX      = 'clang++',
                  CXXFLAGS = ['-std=c++14', '-g',
                              '-Wall', '-Werror', '-Wextra', '-pedantic'])

env.Program('seiken', Glob('*.cpp'))
