from os import environ

env = Environment(ENV       = { 'TERM' : environ['TERM'] },
                  CXX       = 'clang++',
                  CXXFLAGS  = '-std=c++11')

env.Program('sd3.out', Glob('*.cpp'))
